FROM golang:1.26.1-alpine3.23 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o worker ./cmd/worker

FROM alpine:3.23.3
WORKDIR /app
COPY --from=builder /app/worker .

CMD ["./worker"]